name: Haskell CI

on:
  push:
    branches: [ "main", "develop_interpreter" ]
    paths:
      - 'parser/**'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'parser/**'
permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-haskell@v1
      with:
        ghc-version: '8.10.3'
        cabal-version: '3.2'

    - name: Cache
      uses: actions/cache@v3
      env:
        cache-name: cache-cabal
      with:
        path: ~/.cabal
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/*.cabal') }}-${{ hashFiles('**/cabal.project') }}
        restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-name }}-
          ${{ runner.os }}-build-
          ${{ runner.os }}-

    - name: Install dependencies for parser
      run: |
        cd ./parser
        cabal update
        cabal build --only-dependencies --enable-tests --enable-benchmarks
    - name: Build parser
      run: |
        cd ./parser
        cabal build --enable-tests --enable-benchmarks all
    - name: Test parser
      run: |
        cd ./parser
        cabal test parser-test

    - name: Install hlint
      run: |
          cabal update
          cabal install hlint
          hlint .
        
